name: EditionPerms
version: '2.0.0'
main: com.example.editionperms.EditionPerms
api-version: '1.21'
folia-supported: true
author: MistaSoup
description: Advanced permission management for Java and Bedrock players with group support
website: https://github.com/MistaSoup/EditionPerms
commands:
  editionpermsreload:
    description: Reloads the EditionPerms configuration
    usage: /editionpermsreload
    permission: editionperms.reload
    aliases: [epr, epreload, editionreload]
permissions:
  editionperms.reload:
    description: Allows reloading the plugin configuration

    default: op
